modLoader="javafml"
loaderVersion="[43,)"
license="GNU LGPLv3"

[[mods]]
    modId="tanukidecor"
    version="19.2.0.0"
    displayName="Tanuki Decor"
    authors="skyjay1"
    credits=""
    description='''Large furniture mod'''

[[dependencies.tanukidecor]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tanukidecor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"